<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__FILE__, 2);
$baseDir = dirname($vendorDir);

return ['RelativePath' => $vendorDir . '/grandt/relativepath/RelativePath.php', 'com\\grandt\\BinString' => $vendorDir . '/grandt/binstring/BinString.php', 'com\\grandt\\BinStringStatic' => $vendorDir . '/grandt/binstring/BinStringStatic.php'];
