<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__FILE__, 2);
$baseDir = dirname($vendorDir);

return ['ZipMerge\\' => [$vendorDir . '/grandt/phpzipmerge/src/ZipMerge'], 'PHPZip\\Zip\\' => [$vendorDir . '/phpzip/phpzip/src/Zip']];
